require 'json'

Vagrant::Config.run do |config|
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  config.vm.network :hostonly, "192.168.33.11"
  config.vm.customize ["modifyvm", :id, "--memory", 1024]

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = "../../chef/cookbooks"
    chef.roles_path = "../../chef/roles"
    chef.data_bags_path = "../../chef/data_bags"

    chef.add_recipe "apt"

    # Add common solo elements in the Vagrant way
    combinded_json = JSON.parse(File.read("../../chef/solo-nodes/sentry-node.json"))
    combinded_json['run_list'].each { |role| chef.add_role role}
    #chef.json['blah'] = combinded_json['blah']

  end

end
