Vagrant.configure("2") do |config|
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  config.vm.network :private_network, ip: "192.168.33.11"
  # config.vm.network :public_network

  # config.vm.synced_folder "../data", "/vagrant_data"

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
  end

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = "../../chef/cookbooks"
    chef.roles_path = "../../chef/roles"
    chef.data_bags_path = "../../chef/data_bags"

    chef.add_recipe "apt"

    # Add common solo elements in the Vagrant way
    combinded_json = JSON.parse(File.read("../../chef/solo-nodes/sentry-node.json"))
    combinded_json['run_list'].each { |role| chef.add_role role}
    #chef.json['blah'] = combinded_json['blah']

  end

end
